# Generated by Django 3.2.14 on 2022-07-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txn_trackerApp', '0002_address_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date',
        ),
    ]
