# Generated by Django 3.2 on 2022-11-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txn_trackerApp', '0003_remove_address_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='trans_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
